### ISSUE TITLE
install.php could use make_temp_directory()

### ISSUE THREAD

**Issue by mudrd8mz** [tigusigalpa/moodle_admin_tool_imageoptimize#3]
The `make_temp_directory()` might be an appropriate core function to call to make sure that a temporary directory exists.

**Comment by tigusigalpa** [comment]
done :)

**Comment by brendanheywood** [comment]
I'm going to be a little contrary here, make_temp_directory() works on shared datadir which is generally slower for everything. I'd prefer to see this use sys_get_temp_dir() so it's local to whatever frontend processes the file so it will be a lot quicker. Because its local it must be made on demand, it can't in the install.php script

**Comment by tigusigalpa** [comment]
Brendan, absolutely right! Resolved =)

**Comment by mudrd8mz** [comment]
Thank you @brendanheywood for noting this. I can see now this is a good example of the topics you covered in your recent developer meeting talk. Just to clarify, my original point here was that the install.php used to create a directory inside `$CFG->tempdir` "manually" via `mkdir()` call. And so the report was that there is a Moodle API for that.

Do I get it right that the ideal solution here would be to have the optimised images actually cached in two layers?

1. The first layer would be the local cache created on demand via `sys_get_temp_dir()` on each node in a multi-cluster environment.
2. The second layer would be a shared cache created inside `$CFG->tempdir` via `make_temp_directory()`

* When a file is requested, the webserver node should first check the local cache. If it is found there, it should be served and done.
* If the file is not found in the local cache, but it is found in the shared cached, it should be copied over from the shared cached to the local cache and then served.
* If the file is not found in the shared cache, it should be generated first in the local cache, copied over to the shared cache, and then served.

Am I correct here?

**Comment by brendanheywood** [comment]
Nope, the use case here is a temp dir and not a cache dir. A random front end will copy the big image file to it's local temp, reduce it locally, delete the temp files, then ideally (see below) hand it back to core to be saved into the file api.

https://github.com/tigusigalpa/moodle-tool_imageoptimize/blob/62e23d51d8d87b0842a2929c0bd2dee5da921d73/tool_imageoptimize.php#L346-L368

On large clustered file systems writes are around 10x - 100x slower than local disk because you need write locks and communication between gluster nodes.

Under the hood a little more is going on, php first uploads the file to its internal tmp, then moodle grabs it and runs the virus checks on it which can do a bunch of copies, then just before moodle copies it from local temp to the file api (ie filedir) then this intercepts it and does its thing, and ideally in theory replaces it in place, then it hands back to core which copies into the file api. So every time we cross a filesystem mount point boundary there is a copy cost. So you also want the php upload tmp and the sys_get_temp_dir to be as close as possible, which they typically are by default.

Actually I've just noticed another thing:

https://github.com/tigusigalpa/moodle-tool_imageoptimize/blob/62e23d51d8d87b0842a2929c0bd2dee5da921d73/tool_imageoptimize.php#L352

This grabs the whole file contents into memory which will likely explode on some giant file. This should use `add_file_from_path` here:

https://github.com/tigusigalpa/moodle-tool_imageoptimize/blob/62e23d51d8d87b0842a2929c0bd2dee5da921d73/tool_imageoptimize.php#L362

Another issue is that on reflection the core `before_file_created` hook is I think poorly designed - it would have been way simpler if each plugin callback was either passed a reference to the new file record, or it could return a mutated file record:

https://github.com/moodle/moodle/blob/1ab9522055ccba912dcf704a09b858035d4e31cf/lib/filestorage/file_storage.php#L1819

**Comment by mudrd8mz** [comment]
Oh right. Many thanks and sorry for my confusion - clearly I did not recall the purpose of this well and did not bother to re-check before commenting.
