### ISSUE TITLE
Optimize images already uploaded?

### ISSUE THREAD

**Issue by NMCPaul** [tigusigalpa/moodle_admin_tool_imageoptimize#9]
Is there a way to run the plugin against files that are pre-existing on the system, and not just on creation or update?

**Comment by PM84** [comment]
I implemented this functionality for our moodle instance, several month ago, because we have several million images as legacy. We hoped this would reduce load times for users.
The success of the compression can also be quantified via a specially created table. We have found out that for older images the saving of storage space is sometimes more than 80%. With newer images, as expected, significantly lower at 0-20%. On average, we were able to save about 45-55% storage space.
The optimization runs with an scheduled task. #13
